extension_email/urls.py
# coding: utf-8

from django.conf.urls import url
from extension_email import views


urlpatterns = [
    url(r'^from_support/?$', views.FromSupportView.as_view(), name='from-support'),
    url(r'^unsubscribe/(?P<hash_str>.+)/?', views.unsubscribe, name='bulk-unsubscribe'),
    url(r'^api/optout_status/?$', views.OptoutStatusView.as_view(), name='api-optout-status'),
    url(r'^support_mail_template/?$', views.support_mail_template, name='support_mail_template'),
]

extension_email/models.py
# coding: utf-8

from django.db import models
from django.utils.translation import ugettext_lazy as _
from jsonfield import JSONField
from plp.models import User


class SupportEmail(models.Model):
    """
    Модель для сохранения информации и настроек массовой рассылки
    """
    sender = models.ForeignKey(User, verbose_name=_(u'Отправитель'))
    target = JSONField(blank=True, null=True)
    subject = models.CharField(max_length=128, blank=True, verbose_name=_(u'Тема'))
    html_message = models.TextField(null=True, blank=True, verbose_name=_(u'HTML письма'))
    text_message = models.TextField(null=True, blank=True, verbose_name=_(u'Текст письма'))
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _(u'Рассылка')
        verbose_name_plural = _(u'Рассылки')

    def __unicode__(self):
        return '%s - %s' % (self.sender, self.subject)

    def get_recipients(self):
        from .utils import filter_users
        if self.target:
            return filter_users(self)[0]
        return []


class BulkEmailOptout(models.Model):
    user = models.ForeignKey(User, verbose_name=_(u'Пользователь'), related_name='bulk_email_optout')
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name=_(u'Когда пользователь отписался от рассылки'))

    class Meta:
        verbose_name = _(u'Отписка от рассылок')
        verbose_name_plural = _(u'Отписки от рассылок')


class SupportEmailTemplate(models.Model):
    slug = models.CharField(max_length=128, verbose_name=_(u'Название шаблона'), unique=True)
    subject = models.CharField(max_length=128, verbose_name=_(u'Тема'))
    html_message = models.TextField(verbose_name=_(u'HTML письма'))
    text_message = models.TextField(null=True, blank=True, verbose_name=_(u'Текст письма'))

    def __unicode__(self):
        return self.slug

    class Meta:
        verbose_name = _(u'Шаблон рассылки')
        verbose_name_plural = _(u'Шаблоны рассылок')

extension_email/forms.py
# coding: utf-8

from datetime import date
from django import forms
from django.db.models import Case, When, Value, QuerySet, Model
from django.db.models.fields import BooleanField
from django.contrib.admin.widgets import FilteredSelectMultiple, AdminDateWidget
from django.template import Template, Context
from django.utils import timezone
from django.utils.six import text_type
from django.utils.translation import ugettext_lazy as _
from plp.models import CourseSession, Course, University
from .models import SupportEmail, SupportEmailTemplate


class CustomUnicodeCourseSession(CourseSession):
    class Meta:
        proxy = True
        ordering = []

    def __unicode__(self):
        now = timezone.now()
        d = {
            'univ': self.course.university.abbr,
            'course': self.course.title,
            'session': self.slug,
        }
        if self.datetime_starts and self.datetime_ends and self.datetime_starts < now < self.datetime_ends:
            week = (timezone.now().date() - self.datetime_starts.date()).days / 7 + 1
            return u'{univ} - {course} - {session} (неделя {week})'.format(week=week, **d)
        elif self.datetime_starts and self.datetime_starts > now:
            return u'{univ} - {course} - {session} (старт {date})'.format(date=now.strftime('%d.%m.%Y'), **d)
        else:
            return u'{univ} - {course} - {session}'.format(**d)

    @staticmethod
    def get_ordered_queryset():
        now = timezone.now()
        return CustomUnicodeCourseSession.objects.annotate(
            current=Case(
                When(datetime_starts__lt=now, datetime_ends__gt=now, then=Value(True)),
                default=Value(False),
                output_field=BooleanField()
            ),
            future=Case(
                When(datetime_starts__gt=now, then=Value(True)),
                default=False,
                output_field=BooleanField()
            )
        ).order_by('-current', '-future', '-datetime_starts')


class BulkEmailForm(forms.ModelForm):
    """
    Форма для создания массовой рассылки с определенными настройками
    """
    DATETIME_FORMAT = '%d.%m.%Y'
    MIN_DATE = '01.01.2000'
    MAX_DATE = '01.01.2030'
    ENROLLMENT_TYPE_INITIAL = ['paid', 'free']

    chosen_template = forms.ModelChoiceField(
        queryset=SupportEmailTemplate.objects.all(),
        required=False,
        label=_(u'Выберите шаблон или напишите письмо'),
        help_text=_(u'Имейте в виду, что вы не сможете редактировать выбранный шаблон')
    )
    emails = forms.FileField(
        required=False,
        label=_(u'Список емейлов'),
        help_text=_(u'Рассылка по списку игнорируя фильтры. Каждый адрес с новой строки.')
    )
    session_filter = forms.ModelMultipleChoiceField(
        queryset=CustomUnicodeCourseSession.get_ordered_queryset(),
        widget=FilteredSelectMultiple(verbose_name=_(u'Сессии'),
                                      is_stacked=False,
                                      attrs={'style': 'min-height: 180px'}),
        required=False,
        label=_(u'Сессия курса')
    )
    course_filter = forms.ModelMultipleChoiceField(
        queryset=Course.objects.all(),
        widget=FilteredSelectMultiple(verbose_name=_(u'Курсы'),
                                      is_stacked=False,
                                      attrs={'style': 'min-height: 180px'}),
        required=False,
        label=_(u'Курс'),
        help_text=_(u'Отправить письмо подписанным на новости курсов или записанным на них')
    )
    university_filter = forms.ModelMultipleChoiceField(
        queryset=University.objects.all(),
        widget=FilteredSelectMultiple(verbose_name=_(u'Вузы'),
                                      is_stacked=False,
                                      attrs={'style': 'min-height: 180px'}),
        required=False,
        label=_(u'Вуз'),
        help_text=_(u'Отправить письмо подписанным на новости курсов и записанным на курсы этих вузов')
    )
    to_myself = forms.Field(widget=forms.CheckboxInput, label=_(u'Отправить только себе'), required=False,
                           help_text=_(u'Вы получите письмо при отправке только себе даже если вы отписаны от рассылки'))
    last_login_from = forms.DateField(label=_(u'Дата последнего входа от'), widget=AdminDateWidget(),
                                      input_formats=[DATETIME_FORMAT], initial=MIN_DATE)
    last_login_to = forms.DateField(label=_(u'Дата последнего входа до'), widget=AdminDateWidget(),
                                    input_formats=[DATETIME_FORMAT], initial=MAX_DATE)
    register_date_from = forms.DateField(label=_(u'Дата регистрации от'), widget=AdminDateWidget(),
                                         input_formats=[DATETIME_FORMAT], initial=MIN_DATE)
    register_date_to = forms.DateField(label=_(u'Дата регистрации до'), widget=AdminDateWidget(),
                                       input_formats=[DATETIME_FORMAT], initial=MAX_DATE)
    enrollment_type = forms.MultipleChoiceField(choices=(
        ('paid', _(u'Платники')),
        ('free', _(u'Бесплатники'))
    ), widget=forms.CheckboxSelectMultiple, label=_(u'Вариант прохождения'), initial=ENROLLMENT_TYPE_INITIAL)
    got_certificate = forms.MultipleChoiceField(choices=(
        ('paid', _(u'Пользователь получил подтвержденный сертификат')),
        ('free', _(u'Пользователь получил неподтвержденный сертификат')),
    ), widget=forms.CheckboxSelectMultiple, label=_(u'Получен сертификат'), required=False,
       help_text=_(u'Если не выбран ни один из чекбоксов - рассылка для всех пользователей, которые и получили, '
                   u'и не получили сертификаты. Если выбран один чекбокс - то только пользователям платникам либо '
                   u'бесплатникам, получившим сертификат. Если оба - то всем пользователям, получившим сертификат'))

    def __init__(self, *args, **kwargs):
        super(BulkEmailForm, self).__init__(*args, **kwargs)
        self.fields['subject'].required = True
        self.fields['html_message'].required = True
        # chosen_template first
        chosen_template = self.fields.pop('chosen_template')
        root = self.fields._OrderedDict__root
        first = root[1]
        root[1] = first[0] = self.fields._OrderedDict__map['chosen_template'] = [root, first, 'chosen_template']
        dict.__setitem__(self.fields, 'chosen_template', chosen_template)

    def to_json(self):
        data = getattr(self, 'cleaned_data', {})
        result = {}
        for k, v in data.iteritems():
            if k in self.Meta.fields:
                continue
            if isinstance(v, date):
                result[k] = v.strftime(self.DATETIME_FORMAT)
            elif isinstance(v, QuerySet):
                result[k] = [int(i.pk) for i in v]
            elif isinstance(v, Model):
                result[k] = v.pk
            else:
                result[k] = v
        return result

    def clean_emails(self):
        val = self.cleaned_data.get('emails')
        if val:
            result = [i.strip() for i in val.readlines() if i.strip()]
            try:
                text_type(result[0])
            except (UnicodeDecodeError, IndexError):
                raise forms.ValidationError(_(u'Файл не содержит данных или некорректен'))
            return result

    def clean_html_message(self):
        """
        Проверка того, что в HTML тексте корректный джанго шаблон
        """
        html = self.cleaned_data.get('html_message')
        if html:
            try:
                Template(html).render(Context({}))
            except:
                raise forms.ValidationError(_(u'Некорректный HTML текст письма'))
        return html

    def clean(self):
        data = super(BulkEmailForm, self).clean()
        last_login_from = data.get('last_login_from')
        last_login_to = data.get('last_login_to')
        register_date_from = data.get('register_date_from')
        register_date_to = data.get('register_date_to')
        errors = []
        if last_login_from and last_login_to and last_login_from > last_login_to:
            errors.append(_(u'Невозможно отправить рассылку - проверьте корректность дат регистрации'))
        if register_date_from and register_date_to and register_date_from > register_date_to:
            errors.append(_(u'Невозможно отправить рассылку - проверьте корректность дат последнего входа'))
        if errors:
            self._update_errors(forms.ValidationError({'__all__': errors}))
        return data

    class Meta:
        model = SupportEmail
        fields = ['subject', 'html_message']
        widgets = {
            'subject': forms.TextInput(attrs={'style': 'width: 100%'}),
            'html_message': forms.Textarea(attrs={'style': 'width: 100%', 'class': 'vLargeTextField'}),
        }
        help_texts = {
            'html_message': _(u'Можно использовать переменные {{ user.get_full_name }} для подстановки '
                              u'имени и фамилии пользователя в текст, {{ user.first_name }} - имени, '
                              u'{{ user.last_name }} - фамилии, {{ user.email }} - email')
        }

    class Media:
        css = {'all': ['admin/css/widgets.css']}
        js = ['/admin/jsi18n/']

extension_email/templates/extension_email/_css_main.html
<style>
div.form-row {
    position: relative;
    padding-bottom: 20px;
}
p.help {
    position: absolute;
    bottom: 0;
}
</style>

extension_email/templates/extension_email/_js_main.html
{% load static from staticfiles %}
{% load widget_filters i18n admin_static %}

<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
<script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
<script type="text/javascript" src="{% static 'admin/js/calendar.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>
<script type="text/javascript" src="{% static "tiny_mce/tiny_mce.js" %}"></script>
<script type="text/javascript">
    $ = jQuery.noConflict();
    var current_emails_file;
    $(document).on('submit', '#massNewsForm', function (e) {
        e.preventDefault();
        AddRemoveTinyMce('id_html_message');
        $('#id_subject').removeAttr('disabled');
        $('#submitForm').button('loading');
        var formData = new FormData(this);
        formData.append('_check_users_count', '1');
        current_emails_file = $('#id_emails');
        $.ajax({
            url: $(this).attr('action'),
            type: $(this).attr('method'),
            data: formData,
            processData: false,
            contentType: false,
            success: function (data) {
                if (data['form']) {
                    $('#massNewsForm').replaceWith(data['form']);
                    SelectFilter.init("id_session_filter", "Сессия курса", 0, "/static/admin/");
                    SelectFilter.init("id_course_filter", "Курсы", 0, "/static/admin/");
                    SelectFilter.init("id_university_filter", "Вузы", 0, "/static/admin/");
                    DateTimeShortcuts.init();
                    $('#id_emails').replaceWith(current_emails_file);
                }
                if (!data['valid']) {
                    $('body').animate({scrollTop: $('.form-row.errors').first().position().top - $('.global-header').height()});
                    $('#id_emails').replaceWith(current_emails_file);
                    return;
                }
                var msg = data['message'];
                $('#modalDialog div.modal-body').html('<p>' + msg + '</p>');
                $('#modalDialog').modal('show');
            },
            error: function (xhr, err) {
                alert("{% blocktrans %}Во время выполнения запроса произошла ошибка{% endblocktrans %}");
            },
            complete: function(xhr, status) {
                $('#submitForm').button('reset');
                AddRemoveTinyMce('id_html_message');
                template_selected_handler($('#id_chosen_template').val());
            }
        });
        return false;
    });
    $(document).on('click', '#sendMessage', function() {
        SelectBox.select_all('id_session_filter_to');
        SelectBox.select_all('id_course_filter_to');
        SelectBox.select_all('id_university_filter_to');
        var disabled = $('#id_subject').attr('disabled');
        if (disabled)
            $('#id_subject').removeAttr('disabled');
        var form = $('#massNewsForm');
        var formData = new FormData(form[0]);
        $.ajax({
            url: $(form).attr('action'),
            type: $(form).attr('method'),
            data: formData,
            processData: false,
            contentType: false,
            success: function (data) {
                $('#modalDialog').modal('hide');
                alert("{% blocktrans %}Сообщения успешно отправлены{% endblocktrans %}");
            },
            error: function (xhr, err) {
                alert("{% blocktrans %}Во время выполнения запроса произошла ошибка{% endblocktrans %}");
            },
            complete: function(xhr, status) {
                if (disabled) {
                    $('#id_subject').attr('disabled', 'disabled');
                }
            }
        });
    });
    $(document).on('change', '#id_chosen_template', function(e) {
        var val = $(e.target).val();
        if (val) {
            $.post("{% url 'support_mail_template' %}", {id: val}, function(data) {
                $('#id_subject').val(data['subject']);
                tinyMCE.get('id_html_message').setContent(data['html_message'], {format: 'html'});
                template_selected_handler(true);
            });
        }
        else {
            template_selected_handler(false);
            $('#id_subject').val('');
            tinyMCE.get('id_html_message').setContent('', {format: 'html'});
        }
    });
    $(document).on("keydown", function (e) {
        if (e.which === 8 && !$(e.target).is("input, textarea, .redactor-editor")) {
            e.preventDefault();
        }
    });
    function template_selected_handler(selected) {
        var editor = tinymce.get('id_html_message');
        if (selected) {
            $('#id_subject').attr('disabled', 'disabled');
            editor.getBody().setAttribute('contenteditable', false)
            Object.keys(editor.controlManager.controls).forEach(function(btn) {
                editor.controlManager.get(btn).setDisabled(true);
            })
            $(editor.getBody()).delegate('*', 'click', disable_event);
        }
        else {
            $('#id_subject').removeAttr('disabled');
            editor.getBody().setAttribute('contenteditable', true)
            Object.keys(editor.controlManager.controls).forEach(function(btn) {
                editor.controlManager.get(btn).setDisabled(false);
            })
            $(editor.getBody()).undelegate('*', 'click', disable_event);
        }
    }

    function disable_event(e) {
        e.preventDefault();
        return false;
    }

    function AddRemoveTinyMce(editorId) {
        if(tinyMCE.get(editorId))
        {
            tinyMCE.EditorManager.execCommand('mceFocus', false, editorId);
            tinyMCE.EditorManager.execCommand('mceRemoveEditor', true, editorId);

        } else {
            tinymce.EditorManager.execCommand('mceAddEditor', false, editorId);
        }
    }

    function init_redactor() {
         tinymce.init({
            selector: '#id_html_message',
            mode: 'none',
            language: 'ru',
            width: '100%',
            height: '300px',
            plugins: 'fullpage',
          });
    }
    init_redactor();
</script>

extension_email/templates/extension_email/_message_form.html
{% load i18n %}

<form method="post" id="massNewsForm" enctype="multipart/form-data">
    {% csrf_token %}
    {% if form.non_field_errors %}
    <div class="form-row errors">{{ form.non_field_errors }}</div>
    {% endif %}
    <fieldset class="module aligned">
        {% for field in form %}
            {% if field.name == 'session_filter' %}
                <h2>{% blocktrans %}Фильтры{% endblocktrans %}</h2>
            {% endif %}
            <div class="form-row{% if field.errors %} errors{% endif %}">
                <div>
                    <label for="{{ field.name }}">{{ field.label }}</label>{{ field }}
                    {% if field.errors %}{{ field.errors }}{% endif %}
                    {% if field.help_text %}
                        <br><br><p class="help">{{ field.field.help_text|safe }}</p>
                    {% endif %}
                </div>
            </div>
            {% if field.name == 'session_filter' %}
                <h2>{% blocktrans %}Опции для выбора пользователей платформы{% endblocktrans %}</h2>
            {% endif %}
        {% endfor %}
    </fieldset>
    <button type="submit" id="submitForm" class="btn btn-default" data-loading-text="{% blocktrans %}Отправить...{% endblocktrans %}">
        {% blocktrans %}Отправить{% endblocktrans %}</button>
</form>

extension_email/templates/extension_email/base_main.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% load widget_filters i18n admin_static %}

{% block title %}{% blocktrans %}Массовая рассылка{% endblocktrans %}{% endblock title %}

{% block section_id %}bulk_email{% endblock section_id %}

{% block content %}
    <div class="modal fade text-left" tabindex="2" role="dialog" id="modalDialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body"></div>
          <div class="modal-footer">
            <div class="clearfix">
              <span id="sendMessage" class="btn btn-success pull-left">{% blocktrans %}Да{% endblocktrans %}</span>
              <span data-dismiss="modal" class="btn btn-danger pull-right">{% blocktrans %}Нет{% endblocktrans %}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
        <h1>{% blocktrans %}Массовая рассылка{% endblocktrans %}</h1>
        {% include 'extension_email/_message_form.html' %}
        <br>
    </div>
{% endblock %}

{% block page_header %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/SelectFilter2.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/SelectBox.js' %}"></script>
{% endblock %}

extension_email/templates/extension_email/main.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% load widget_filters i18n admin_static %}

{% block title %}{% blocktrans %}Массовая рассылка{% endblocktrans %}{% endblock title %}

{% block section_id %}bulk_email{% endblock section_id %}

{% block content %}
    <div class="modal fade text-left" tabindex="2" role="dialog" id="modalDialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body"></div>
          <div class="modal-footer">
            <div class="clearfix">
              <span id="sendMessage" class="btn btn-success pull-left">{% blocktrans %}Да{% endblocktrans %}</span>
              <span data-dismiss="modal" class="btn btn-danger pull-right">{% blocktrans %}Нет{% endblocktrans %}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
        <h1>{% blocktrans %}Массовая рассылка{% endblocktrans %}</h1>
        {% include 'extension_email/_message_form.html' %}
        <br>
    </div>
{% endblock %}

{% block page_header %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/SelectFilter2.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/SelectBox.js' %}"></script>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
    <script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
    <script type="text/javascript" src="{% static 'admin/js/calendar.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>
    <script type="text/javascript" src="{% static "tiny_mce/tiny_mce.js" %}"></script>
    <script type="text/javascript">
        $ = jQuery.noConflict();
        var current_emails_file;
        $(document).on('submit', '#massNewsForm', function (e) {
            e.preventDefault();
            AddRemoveTinyMce('id_html_message');
            $('#id_subject').removeAttr('disabled');
            $('#submitForm').button('loading');
            var formData = new FormData(this);
            formData.append('_check_users_count', '1');
            current_emails_file = $('#id_emails');
            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: formData,
                processData: false,
                contentType: false,
                success: function (data) {
                    if (data['form']) {
                        $('#massNewsForm').replaceWith(data['form']);
                        SelectFilter.init("id_session_filter", "Сессия курса", 0, "/static/admin/");
                        SelectFilter.init("id_course_filter", "Курсы", 0, "/static/admin/");
                        SelectFilter.init("id_university_filter", "Вузы", 0, "/static/admin/");
                        DateTimeShortcuts.init();
                        $('#id_emails').replaceWith(current_emails_file);
                    }
                    if (!data['valid']) {
                        $('body').animate({scrollTop: $('.form-row.errors').first().position().top - $('.global-header').height()});
                        $('#id_emails').replaceWith(current_emails_file);
                        return;
                    }
                    var msg = data['message'];
                    $('#modalDialog div.modal-body').html('<p>' + msg + '</p>');
                    $('#modalDialog').modal('show');
                },
                error: function (xhr, err) {
                    alert("{% blocktrans %}Во время выполнения запроса произошла ошибка{% endblocktrans %}");
                },
                complete: function(xhr, status) {
                    $('#submitForm').button('reset');
                    AddRemoveTinyMce('id_html_message');
                    template_selected_handler($('#id_chosen_template').val());
                }
            });
            return false;
        });
        $(document).on('click', '#sendMessage', function() {
            SelectBox.select_all('id_session_filter_to');
            SelectBox.select_all('id_course_filter_to');
            SelectBox.select_all('id_university_filter_to');
            var disabled = $('#id_subject').attr('disabled');
            if (disabled)
                $('#id_subject').removeAttr('disabled');
            var form = $('#massNewsForm');
            var formData = new FormData(form[0]);
            $.ajax({
                url: $(form).attr('action'),
                type: $(form).attr('method'),
                data: formData,
                processData: false,
                contentType: false,
                success: function (data) {
                    $('#modalDialog').modal('hide');
                    alert("{% blocktrans %}Сообщения успешно отправлены{% endblocktrans %}");
                },
                error: function (xhr, err) {
                    alert("{% blocktrans %}Во время выполнения запроса произошла ошибка{% endblocktrans %}");
                },
                complete: function(xhr, status) {
                    if (disabled) {
                        $('#id_subject').attr('disabled', 'disabled');
                    }
                }
            });
        });
        $(document).on('change', '#id_chosen_template', function(e) {
            var val = $(e.target).val();
            if (val) {
                $.post("{% url 'support_mail_template' %}", {id: val}, function(data) {
                    $('#id_subject').val(data['subject']);
                    tinyMCE.get('id_html_message').setContent(data['html_message'], {format: 'html'});
                    template_selected_handler(true);
                });
            }
            else {
                template_selected_handler(false);
                $('#id_subject').val('');
                tinyMCE.get('id_html_message').setContent('', {format: 'html'});
            }
        });
        $(document).on("keydown", function (e) {
            if (e.which === 8 && !$(e.target).is("input, textarea, .redactor-editor")) {
                e.preventDefault();
            }
        });
        function template_selected_handler(selected) {
            var editor = tinymce.get('id_html_message');
            if (selected) {
                $('#id_subject').attr('disabled', 'disabled');
                editor.getBody().setAttribute('contenteditable', false)
                Object.keys(editor.controlManager.controls).forEach(function(btn) {
                    editor.controlManager.get(btn).setDisabled(true);
                })
                $(editor.getBody()).delegate('*', 'click', disable_event);
            }
            else {
                $('#id_subject').removeAttr('disabled');
                editor.getBody().setAttribute('contenteditable', true)
                Object.keys(editor.controlManager.controls).forEach(function(btn) {
                    editor.controlManager.get(btn).setDisabled(false);
                })
                $(editor.getBody()).undelegate('*', 'click', disable_event);
            }
        }

        function disable_event(e) {
            e.preventDefault();
            return false;
        }

        function AddRemoveTinyMce(editorId) {
            if(tinyMCE.get(editorId))
            {
                tinyMCE.EditorManager.execCommand('mceFocus', false, editorId);
                tinyMCE.EditorManager.execCommand('mceRemoveEditor', true, editorId);

            } else {
                tinymce.EditorManager.execCommand('mceAddEditor', false, editorId);
            }
        }

        function init_redactor() {
             tinymce.init({
                selector: '#id_html_message',
                mode: 'none',
                language: 'ru',
                width: '100%',
                height: '300px',
                plugins: 'fullpage',
              });
        }
        init_redactor();
    </script>
{% endblock %}

{% block styling %}
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}"/>
    {{ block.super }}
    <style>
    div.form-row {
        position: relative;
        padding-bottom: 20px;
    }
    p.help {
        position: absolute;
        bottom: 0;
    }
    </style>
{% endblock %}

extension_email/templates/extension_email/main_miptx.html
{% extends 'extension_email/base_main.html' %}
{% load static from staticfiles %}

{% load widget_filters i18n admin_static %}

{% block js %}
    {{ block.super }}
    {% include 'extension_email/_js_main.html' %}
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}"/>
    {{ block.super }}
    {% include 'extension_email/_css_main.html' %}
{% endblock %}